config:
  send_anonymous_usage_stats: False
  use_colors: True
  partial_parse: True

dbt_example:
  outputs:
    ci:
      type: postgres
      schema: dbt
      host: "{{ env_var('DBT_HOST') }}"
      port: 6432
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      secure: True
      verify: False
    dev:
      type: postgres
      threads: 1
      host: postgres
      port: 5432
      user: postgres
      pass: postgres
      dbname: postgres
      schema: dbt
  target: dev
